### ISSUE TITLE
JSON Schema validator/linter

### ISSUE THREAD

**Issue by philtay** [fidor/fidor_schema#7]
It looks like you are using JSON Schema draft v4 to describe your API (e.g. the use of the new _oneOf_ keyword in transaction.json). Unfortunately almost none of your schemas validates against the JSON Schema draft v4 meta-schema. Basically they are unusable with any library which cares about the standard. Could you please use a validator/linter on your schemas, fix the errors and then release a new version? Just google and you will find a lot of them. This is one: http://json-schema-validator.herokuapp.com/syntax.jsp. For instance, _required_ must be a first level keyword and not an attribute of subschemas (https://github.com/json-schema/json-schema/wiki/ChangeLog#required), you can't use a $ref in places like this: https://github.com/fidor/fidor_schema/blob/master/schema/v1.0/account.json#L72 because an object is expected, etc. Moreover using the $schema keyword at the root of your schemas would be a very good thing to do. Now I have to guess if your schemas are JSON Schema draft v4 or v3.

**Comment by schorsch** [comment]
good points, thanks for the input. Already had a couple of rounds on it so another one won't hurt

**Comment by philtay** [comment]
Yep, it definitely won't hurt! Please keep in mind that if the schemas don't validate they are useless. Every piece of software out there expects a valid standard schema. If you are using the linter I suggested (http://json-schema-validator.herokuapp.com/syntax.jsp), please note that you can ignore all the errors relative to URI normalization. If you don't want to see them just put an "http://" in front of the URI and they will go away. All the other errors must be fixed in order to have usable schemas. Please also don't forget the root $schema keyword. Should you need a hand with all of this just let me know. Thanks
