### ISSUE TITLE
date-time values

### ISSUE THREAD

**Issue by philtay** [fidor/fidor_schema#8]
Please use valid date-time values in your API. The JSON Schema specification mandates RFC 3339 format. Currently you are using a format that is not even ISO 8601 compliant. Thanks

http://json-schema.org/latest/json-schema-validation.html#anchor108

**Comment by agalloch** [comment]
Hello, @philtay, would you be more specific as to what ISO 8601 compliance you refer to? Like for example, a typical date representation we use is `"created_at": "2013-01-31T18:34:25Z"` which is a UTC date-time ([source](https://en.wikipedia.org/wiki/ISO_8601)).

**Comment by philtay** [comment]
dunno what you use now, this issue is more than 1 year old. please close it (especially if now you are RFC 3339 compliant).
